---
layout: post
toc: true
title: ML, NBA Data
description: 
courses: { csp: {week: 25} }
type: ccc
---

In [18]:
# Uncomment the following lines to install the required packages
!pip install opendatasets
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: opendatasets in /Users/rayanesouissi/Library/Python/3.9/lib/python/site-packages (0.1.22)
Requirement already satisfied: tqdm in /Users/rayanesouissi/Library/Python/3.9/lib/python/site-packages (from opendatasets) (4.66.2)
Requirement already satisfied: kaggle in /Users/rayanesouissi/Library/Python/3.9/lib/python/site-packages (from opendatasets) (1.6.6)
Requirement already satisfied: click in /Users/rayanesouissi/Library/Python/3.9/lib/python/site-packages (from opendatasets) (8.1.7)
Requirement already satisfied: six>=1.10 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from kaggle->opendatasets) (1.15.0)
Requirement already satisfied: certifi in /Users/rayanesouissi/Library/Python/3.9/lib/python/site-packages (from kaggle->opendatasets) (2023.7.22)
Requirement already satisfied: python-dateutil in /Users/rayanesouissi/Library/Python/3.9/lib/python/site-packages (from kaggle->opendatasets) (2.8.2)
Requirement already satisfied: requests in /Users/rayanesouissi/Library/Python/3.9/lib/python/site-packages (from kaggle->opendatasets) (2.31.0)
Requirement already satisfied: python-slugify in /Users/rayanesouissi/Library/Python/3.9/lib/python/site-packages (from kaggle->opendatasets) (8.0.4)
Requirement already satisfied: urllib3 in /Users/rayanesouissi/Library/Python/3.9/lib/python/site-packages (from kaggle->opendatasets) (2.0.7)
Requirement already satisfied: bleach in /Users/rayanesouissi/Library/Python/3.9/lib/python/site-packages (from kaggle->opendatasets) (6.1.0)
Requirement already satisfied: webencodings in /Users/rayanesouissi/Library/Python/3.9/lib/python/site-packages (from bleach->kaggle->opendatasets) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in /Users/rayanesouissi/Library/Python/3.9/lib/python/site-packages (from python-slugify->kaggle->opendatasets) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/rayanesouissi/Library/Python/3.9/lib/python/site-packages (from requests->kaggle->opendatasets) (3.3.1)
Requirement already satisfied: idna<4,>=2.5 in /Users/rayanesouissi/Library/Python/3.9/lib/python/site-packages (from requests->kaggle->opendatasets) (3.4)

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /Users/rayanesouissi/Library/Python/3.9/lib/python/site-packages (2.2.1)
Requirement already satisfied: numpy<2,>=1.22.4 in /Users/rayanesouissi/Library/Python/3.9/lib/python/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/rayanesouissi/Library/Python/3.9/lib/python/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/rayanesouissi/Library/Python/3.9/lib/python/site-packages (from pandas) (2023.4)
Requirement already satisfied: tzdata>=2022.7 in /Users/rayanesouissi/Library/Python/3.9/lib/python/site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip

In [19]:
import opendatasets as od
import pandas

od.download('https://www.kaggle.com/datasets/vivovinco/20222023-nba-player-stats-regular')

Skipping, found downloaded files in "./20222023-nba-player-stats-regular" (use force=True to force download)

'{"username":"rayanesouissi","key":"e3f3bbe826834d5b209084ba2714f3fe"}\n'

In [46]:
import pandas as pd

df = pd.read_csv('20222023-nba-player-stats-regular/2022-2023 NBA Player Stats - Playoffs.csv', encoding='cp1252', sep=';')

df

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Bam Adebayo,C,25,MIA,23,23,37.0,7.3,15.1,...,0.821,2.7,7.1,9.9,3.7,0.9,0.7,2.7,3.1,17.9
1,2,Santi Aldama,PF,22,MEM,6,0,16.8,2.5,5.5,...,1.000,1.2,3.2,4.3,1.2,0.5,0.0,0.3,0.8,6.5
2,3,Nickeil Alexander-Walker,SG,24,MIN,5,4,29.6,3.0,7.0,...,0.667,0.2,1.8,2.0,1.4,0.6,0.2,0.8,1.8,8.4
3,4,Grayson Allen,SG,27,MIL,5,5,29.8,3.8,8.2,...,0.857,0.2,2.2,2.4,1.8,0.4,0.0,0.8,1.4,11.6
4,5,Jarrett Allen,C,24,CLE,5,5,38.2,4.4,7.2,...,0.500,3.0,4.4,7.4,2.4,0.8,1.0,0.6,2.0,9.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,213,Ziaire Williams,SF,21,MEM,4,0,3.0,0.5,1.8,...,0.000,0.0,0.5,0.5,0.5,0.0,0.0,0.5,0.3,1.3
213,214,Trae Young,PG,24,ATL,6,6,38.3,10.0,24.8,...,0.860,0.8,2.8,3.7,10.2,1.7,0.7,4.0,1.8,29.2
214,215,Omer Yurtseven,C,24,MIA,8,0,2.0,0.3,0.9,...,0.000,0.4,0.3,0.6,0.1,0.0,0.1,0.1,0.3,0.5
215,216,Cody Zeller,C,30,MIA,21,0,8.3,1.0,1.7,...,0.400,0.5,1.8,2.3,0.3,0.1,0.2,0.6,1.3,2.2
216,217,Ivica Zubac,C,25,LAC,5,5,26.0,3.4,6.0,...,0.750,3.2,6.4,9.6,0.6,0.6,0.2,2.2,1.6,9.2

#### Median PPG Among NBA Players

In [21]:
df['PTS'].median()

6.5

#### Range (Maximum - Minimum Values) of NBA Players

In [25]:
df['PTS'].max() - df['PTS'].min()

34.5

#### Average Field Goals Made Among Players

In [24]:
df['FG'].mean()

3.193548387096774

In [61]:
X_train

,Age,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF
82,25,15,0,6.9,0.7,1.9,0.345,0.5,1.6,0.333,0.1,0.3,0.400,0.483,0.1,0.1,1.000,0.3,0.8,1.1,0.3,0.1,0.1,0.0,0.5
65,27,20,20,35.7,5.1,9.8,0.518,0.9,2.3,0.391,4.2,7.5,0.557,0.564,2.3,3.5,0.652,2.5,3.6,6.0,2.6,0.6,0.7,1.0,2.9
109,25,6,0,5.2,0.3,0.8,0.400,0.2,0.7,0.250,0.2,0.2,1.000,0.500,0.0,0.0,0.000,0.2,0.8,1.0,0.0,0.2,0.2,0.3,0.5
183,25,10,1,18.4,1.7,4.5,0.378,1.1,2.9,0.379,0.6,1.6,0.375,0.500,0.3,0.4,0.750,0.3,1.4,1.7,1.1,0.2,0.1,0.4,1.5
31,33,22,22,39.7,9.4,20.1,0.468,1.3,3.5,0.359,8.1,16.5,0.492,0.500,6.8,8.5,0.806,2.1,4.3,6.5,5.9,1.8,0.6,1.9,1.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,25,3,0,3.7,0.0,0.7,0.000,0.0,0.3,0.000,0.0,0.3,0.000,0.000,0.7,0.7,1.000,0.0,0.3,0.3,0.3,0.0,0.0,0.3,0.0
14,34,5,3,18.4,1.6,3.8,0.421,1.2,3.4,0.353,0.4,0.4,1.000,0.579,0.0,0.0,0.000,0.2,2.0,2.2,1.2,0.4,0.4,0.4,2.0
92,35,5,0,17.8,2.4,4.6,0.522,2.0,4.0,0.500,0.4,0.6,0.667,0.739,0.0,0.0,0.000,0.2,1.0,1.2,2.0,0.6,0.2,1.2,1.4
179,32,3,0,5.7,0.0,0.3,0.000,0.0,0.0,0.000,0.0,0.3,0.000,0.000,0.0,0.0,0.000,0.7,1.3,2.0,1.0,0.3,0.0,1.7,1.7
102,19,7,0,1.9,0.1,0.6,0.250,0.0,0.3,0.000,0.1,0.3,0.500,0.250,0.0,0.0,0.000,0.1,0.6,0.7,0.0,0.0,0.0,0.0,0.0

In [65]:
#Clean data
df_new = df[['Age', 'FG', 'FG%', '3P', '3P%', 'FT', 'FT%']]

df_new

     Age    FG    FG%   3P    3P%   FT    FT%
0     25   7.3  0.481  0.0  0.000  3.4  0.821
1     22   2.5  0.455  1.2  0.467  0.3  1.000
2     24   3.0  0.429  2.0  0.400  0.4  0.667
3     27   3.8  0.463  2.8  0.483  1.2  0.857
4     24   4.4  0.611  0.0  0.000  0.6  0.500
..   ...   ...    ...  ...    ...  ...    ...
212   21   0.5  0.286  0.3  0.333  0.0  0.000
213   24  10.0  0.403  3.0  0.333  6.2  0.860
214   24   0.3  0.286  0.0  0.000  0.0  0.000
215   30   1.0  0.571  0.0  0.000  0.3  0.400
216   25   3.4  0.567  0.0  0.000  2.4  0.750

[217 rows x 7 columns]

In [66]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

def replace_score(score):
    if score > 10:
        return 1
    else:
        return 0

# Build distinct data frames on PTS column
x = df_new
y = df['PTS'].apply(replace_score)

# Split arrays in random train 70%, random test 30%, using stratified sampling (same proportion of survived in both sets) and a fixed random state (42
# The number 42 is often used in examples and tutorials because of its cultural significance in fields like science fiction (it's the "Answer to the Ultimate Question of Life, The Universe, and Everything" in The Hitchhiker's Guide to the Galaxy by Douglas Adams). But in practice, the actual value doesn't matter; what's important is that it's set to a consistent value.
# X_train is the DataFrame containing the features for the training set.
# X_test is the DataFrame containing the features for the test set.
# y-train is the 'survived' status for each passenger in the training set, corresponding to the X_train data.
# y_test is the 'survived' status for each passenger in the test set, corresponding to the X_test data.
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

# Train a decision tree classifier
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

# Test the model
y_pred = dt.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print('DecisionTreeClassifier Accuracy: {:.2%}'.format(accuracy))  

# Train a logistic regression model
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

# Test the model
y_pred = logreg.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print('LogisticRegression Accuracy: {:.2%}'.format(accuracy))

DecisionTreeClassifier Accuracy: 93.94%
LogisticRegression Accuracy: 98.48%

### Predicting Survival
So, now we are ready to play the game... "Would I have survived the Titanic?".  

Insert your own data in the code.  Look at your analysis and consider how you would travel today.
- Data description:
    - pclass - Passenger Class (1 = 1st; 2 = 2nd; 3 = 3rd)
    - name - Name
    - sex - male or female
    - age - number of year 
    - sibsp - number of Siblings/Spouses Aboard
    - parch - number of Parents/Children Aboard
    - fare - passenger fare 0 to 512
    - embarked - Port of Embarkation (C = Cherbourg; Q = Queenstown; S = Southampton)
    - alone - boolean True or False

In [80]:
import numpy as np

# Logistic regression model is used to predict the probability

# Define a new player
player = pd.DataFrame({
    'Age': [25],
    'FG': [8], 
    'FG%': [.50],
    '3P': [4],
    '3P%': [.20], 
    'FT': [6], 
    'FT%': [1], 
})

display(player)
new_player = player.copy()
display(new_player)

# Predict the survival probability for the new passenger
dead_proba, alive_proba = np.squeeze(logreg.predict_proba(new_player))

# Print the survival probability
print('<10 probability: {:.2%}'.format(dead_proba))  
print('>10 probability: {:.2%}'.format(alive_proba))

   Age  FG  FG%  3P  3P%  FT  FT%
0   25   8  0.5   4  0.2   6  0.9

   Age  FG  FG%  3P  3P%  FT  FT%
0   25   8  0.5   4  0.2   6  0.9

<10 probability: 0.00%
>10 probability: 100.00%

### Improve your chances
Is there anything you could do to improve your chances?

In [ ]:
# Decision tree model is used to determine the importance of each feature

importances = dt.feature_importances_
for feature, importance in zip(new_passenger.columns, importances):
    print(f'The importance of {feature} is: {importance}')